sudo: required
dist: trusty

language: generic

services:
  - docker

before_install:
  - sudo apt-get update && sudo apt-get install -y realpath bc

env:
  matrix:
    - D=./examples/ex01 CSV=ex01.csv N=5
    - D=./moby CSV=moby.csv N=5 REPO=https://github.com/moby/moby.git ONLY_DOCKER=1
    - D=./moby CSV=moby.csv N=5 REPO=https://github.com/moby/moby.git ONLY_BUILDKIT=1
    - D=./moby CSV=moby.csv N=5 REPO=https://github.com/moby/moby.git ONLY_IMG=1

# moby/moby is the good example of complex Dockerfile.
# However, as of June 5, 2018, Buildah and Kaniko does not support `FROM anotherstage`.

script:
  - |
    if [ ! -z ${REPO} ]; then
      git clone ${REPO} ${D}
      ( cd ${D} ;  git show --summary )
    fi
  - echo "travis_fold:start:buildbench"
  - ./buildbench ${D} ${CSV} ${N}
  - echo "travis_fold:end:buildbench"
  - cat ${CSV}
